name: 13 if condition
on: 
    push:
        branches:
        - main

    pull_request:
        branches:
        - develop

jobs:
    job1-basics:
        runs-on: ubuntu-latest
        steps:
            - name: Run if branch is main (curly brackets)
              if: ${{ github.ref == 'refs/heads/main' }} 
              run: echo "Running this step"

            - name: Run if branch is main (no curly brackets)
              if: github.ref == 'refs/heads/main' 
              run: echo "Running this step"

            - name: Run if branch is main (no curly brackets)
              if: github.ref_name == 'main' 
              run: echo "Running this step"

            - name: Run this step 
              run: echo "Running this step"

    jo2_with_or_condition:
        runs-on: ubuntu-latest
        steps:
            - name: Run for Dawiden1
              if: github.actor == 'Dawiden1' || github.actor == 'Ned1vad47'
              run: |
                echo "It is triggered by either Dawiden1 or Ned1vad47"
                echo "Github actor is ${{ github.actor }}"

# More examples of using if conditions on JOB LEVEL
#    - Run "Build Job" when pull request is raised
#    - Run "Deploy Job" when commits are pushed to main

    build-job: 
        if: ${{ github.event_name == 'pull_request' }}
        runs-on: ubuntu-latest
        steps:
            - name: dd
              run: echo "Build Job"

    deploy-job: 
        if:  ${{ github.event_name == 'push' }}
        needs: build-job
        runs-on: ubuntu-latest
        steps:
            - name: ee
              run: echo "Deploy Job"