name: Reusable Workflow
on:
    workflow_call:
    # it makes it reusable
        inputs:
            name:
                description: Enter the name
                required: true
                type: string 

jobs:
    greeting:
        runs-on: ubuntu-latest
        steps:
            - name: Greeting step
              run: echo "Welcome ${{ inputs.name }} to Reusable Workflow"