name: Reusable Workflow
on:
    workflow_call:
    # it makes it reusable

jobs:
    greeting:
        runs-on: ubuntu-latest
        steps:
            - name: Greeting step
              run: echo "Welcome to Reusable Workflow"