name: 4 push & pr_trigger
on: 
    push:
        branches:
            - develop
            - 'release/**'
    pull_request:
      types:
        - opened
        - reopened
      branches:
        - main                  # when PR is raised against main branch, it's gonna trigger the workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "A demo build"
