name: 5 using variable

on: push

jobs:
  job1_printing_variable:
    runs-on: ubuntu-latest
    steps:
      - name: step1_helloWorld_name
        run: echo "My first variable is ${{ vars.MY_VAR_NAME }}"