name: 7 static deploy HTML to s3 bucket
on: workflow_dispatch
jobs:
    deployHTMLtoS3:
        runs-on: ubuntu-latest
        steps:

            # It must be included to allow VM access to the repo
            - name: Checkout code from repo 
              uses: actions/checkout@v4
            
            # GHA requires permisions to send a HTML code. This action takes some inputs 
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_SECRET_KEY_ID }}
                aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                aws-region: eu-west-2

            #Copy static website code onto S3 bucket 
            - name: Deploy S3 file
              run: |
                aws s3 sync ./ s3://dawidm-github-actions-demo-bucket \
                --exclude "*" \
                --include "index.html"