name: 8 env demo

on: workflow_dispatch

env:
    APP_ENV: "DEV"
    LEVEL: "WORKFLOW"

jobs:
    env_demo_WORKFLOW_LEVEL:
        runs-on: ubuntu-latest
        steps:
            - name: Connecting to Env
              run: echo "App is connecting to $APP_ENV"

    env_demo_JOB_LEVEL:
        env:
            APP_ENV: "TEST"
        runs-on: ubuntu-latest
        steps:
            - name: Connecting to Env
              run: echo "App is connecting to $APP_ENV"

    env_demo_STEP_LEVEL:
        runs-on: ubuntu-latest
        steps:
            - name: Connecting to Env
              env:
                APP_ENV: "PROD"
              run: echo "App is connecting to $APP_ENV"

    env_demo_MIXED_CHECK:
        runs-on: ubuntu-latest
        env:
            LEVEL: "JOB > WORKFLOW"
        steps:
            - name: Connecting to Env
              env:
                LEVEL: "STEP > JOB > WORKFLOW"
              run: echo "App is connecting to $LEVEL"


 